fix make distcheck
The dependency of the distributed file stow.8 on the non-distributed
file Makefile was causing this error:

    ERROR: files left in build directory after distclean:
    ./doc/stow.8

The automake FAQ explains why this happens:

    https://www.gnu.org/software/automake/manual/html_node/Errors-with-distclean.html

so change stow.8 to depend on Makefile.am which is distributed.