More fixes to "make distcheck"
As with dc6a141d, the dependency of distributed files on non-distributed
files was causing this error:

    ERROR: files left in build directory after distclean:

The automake FAQ explains why this happens:

    https://www.gnu.org/software/automake/manual/html_node/Errors-with-distclean.html

so change the dependency to Makefile.am which is distributed.